# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Research
    PageRef: research.md
    weight: 20
  - name: Publications
    PageRef: publication/_index.md
    weight: 30
  - name: Teach
    PageRef: teach.md
    weight: 40
  - name: Tutorial
    weight: 50
    identifier: courses
  - name: CVPR 24'
    PageRef: course/cvpr/_index.md
    weight: 60
    parent: courses
  # - name: Robotics
  #   PageRef: course/robotics/_index.md
  #   weight: 20
  #   parent: courses

  # - name: Contact
  #   PageRef: contact/index.md
  #   weight: 60
